"""Create the initial Edgefinder schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-07-12 22:57:08.173926

"""
from alembic import op
import sqlalchemy as sa


revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'DRAFT', 'PUBLISHED', 'FAILED', name='runstatus', native_enum=False), nullable=False),
    sa.Column('cutoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_cost_eur', sa.Float(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('signal_ids_seen', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_runs_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_runs_status'), ['status'], unique=False)

    op.create_table('sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('region', sa.String(length=40), nullable=False),
    sa.Column('base_url', sa.String(length=1000), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('quality', sa.Float(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_key'), ['key'], unique=True)

    op.create_table('opportunities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('canonical_key', sa.String(length=180), nullable=False),
    sa.Column('kind', sa.Enum('RANKED', 'WATCH', name='opportunitykind', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'VALIDATE', 'WATCH', 'REJECT', 'SEEN_BEFORE', name='opportunitystatus', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('buyer', sa.Text(), nullable=False),
    sa.Column('observed_pain', sa.Text(), nullable=False),
    sa.Column('proposed_wedge', sa.Text(), nullable=False),
    sa.Column('why_now', sa.Text(), nullable=False),
    sa.Column('norway_advantage', sa.Text(), nullable=False),
    sa.Column('global_path', sa.Text(), nullable=False),
    sa.Column('business_model', sa.Text(), nullable=False),
    sa.Column('risks', sa.JSON(), nullable=False),
    sa.Column('validation_effort', sa.Text(), nullable=False),
    sa.Column('next_experiment', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=False),
    sa.Column('update_of_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['update_of_id'], ['opportunities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunities_canonical_key'), ['canonical_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_status'), ['status'], unique=False)
        batch_op.create_index('ix_opportunity_score', ['score'], unique=False)

    op.create_table('signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=500), nullable=False),
    sa.Column('canonical_url', sa.String(length=2000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=12), nullable=False),
    sa.Column('region', sa.String(length=40), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('suspicious_instructions', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_signal_source_external')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_canonical_url'), ['canonical_url'], unique=False)
        batch_op.create_index('ix_signals_content_hash', ['content_hash'], unique=False)
        batch_op.create_index('ix_signals_observed_at', ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_source_id'), ['source_id'], unique=False)

    op.create_table('agent_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('verdict', sa.String(length=40), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('score_delta', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_reviews_opportunity_id'), ['opportunity_id'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('signal_id', sa.String(length=36), nullable=True),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('stance', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=False),
    sa.Column('source_name', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_signal_id'), ['signal_id'], unique=False)

    op.create_table('feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.Enum('NEW', 'VALIDATE', 'WATCH', 'REJECT', 'SEEN_BEFORE', name='opportunitystatus', native_enum=False), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_opportunity_id'), ['opportunity_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_opportunity_id'))

    op.drop_table('feedback')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_signal_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_opportunity_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('agent_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_reviews_opportunity_id'))

    op.drop_table('agent_reviews')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_source_id'))
        batch_op.drop_index('ix_signals_observed_at')
        batch_op.drop_index('ix_signals_content_hash')
        batch_op.drop_index(batch_op.f('ix_signals_canonical_url'))

    op.drop_table('signals')
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_index('ix_opportunity_score')
        batch_op.drop_index(batch_op.f('ix_opportunities_status'))
        batch_op.drop_index(batch_op.f('ix_opportunities_run_id'))
        batch_op.drop_index(batch_op.f('ix_opportunities_canonical_key'))

    op.drop_table('opportunities')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_key'))

    op.drop_table('sources')
    with op.batch_alter_table('research_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_runs_status'))
        batch_op.drop_index(batch_op.f('ix_research_runs_published_at'))

    op.drop_table('research_runs')
    # ### end Alembic commands ###
